version: '3'

services:

  donut:
    image: donut:${TAG:-dev}
    container_name: donut
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - API_AUTHORITY=${API_AUTHORITY}
      - API_NAME=${API_NAME}
      - API_SECRET=${API_SECRET},
      - ASSETACCOUNTSERVICEHOST=${ASSETACCOUNTSERVICEHOST:-http://terminal-matching-engine},
      - USERSERVICEHOST=${USERSERVICEHOST:-http://terminal-matching-engine}
    env_file:
      - ./default.env
    build:
      context: ../Donut/
      dockerfile: VisualStudio.Dockerfile
      args:
        version: ${VERSION:-0.1.0-developer}
    volumes:
      - ${LOG_PATH:-/logs}:/app/logs
